name: "Run ECS task"
description: "GitHub Action to run a task on Amazon ECS and output CloudWatch Logs"
author: w40141
branding:
  icon: "cloud"
  color: "orange"

inputs:
  cluster:
    description: "ECS Cluster name"
    required: true
  task-definition:
    required: true
    description: "The task definition name"
  task-definition-family:
    description: "The name for your task definition"
    required: true
  security-groups:
    description: "awsvpcConfiguration values: ['sg-00', ...]"
    required: true
  subnets:
    description: "awsvpcConfiguration values: ['subnet-00', ...]"
    required: true
  assign-public-ip:
    description: "awsvpcConfiguration values"
    required: false
    default: "DISABLED"
  command:
    description: "Overrides the default command from the Docker image or the task definition. This parameter is required if any override is specified."
    required: false
  container-name:
    description: "The name of the container that run command. This parameter is required if any override is specified."
    required: false
  launch-type:
    description: "Launch type"
    required: false
    default: "FARGATE"
  region:
    description: "AWS Region"
    required: false
    default: "ap-northeast-1"

outputs:
  task-id:
    description: "Task ID"
    value: ${{ steps.run-task.outputs.task_id }}
  revision:
    description: "Task definition's revision number"
    value: ${{ steps.task-def-register.outputs.revision }}
  logs:
    description: "CloudWatch Logs"
    value: ${{ steps.logs.outputs.out }}

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        if ! [ -x "$(command -v aws)" ]; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          awscli --version
        fi

    - name: Register ECS task definition
      shell: bash
      id: task-def-register
      run: |
        revision=$(aws ecs register-task-definition \
          --region ${{ inputs.region }} \
          --family ${{ inputs.task-definition-family }} \
          --cli-input-json file://${{ inputs.task-definition }} \
          --query taskDefinition.revision)
        echo "revision=$revision" >> $GITHUB_OUTPUT

    - name: Run ECS task
      shell: bash
      id: run-task
      env:
        vpc_configuration: "{subnets=${{ inputs.subnets }},securityGroups=${{ inputs.security-groups }},assignPublicIp=${{ inputs.assign-public-ip }}}"
        container_overrides: '{"containerOverrides": [{"name": "${{ inputs.container-name}}", "command": ${{ inputs.command }} }]}'
      run: |
        if [ '${{ inputs.container-name }}' != '' ] && [ '${{ inputs.command }}' != '' ]; then
          task_arn=$(aws ecs run-task \
            --cluster ${{ inputs.cluster }} \
            --launch-type ${{ inputs.launch-type }} \
            --network-configuration 'awsvpcConfiguration=${{ env.vpc_configuration }}' \
            --output text \
            --overrides '${{ env.container_overrides }}' \
            --query tasks[0].taskArn \
            --region ${{ inputs.region }} \
            --task-definition ${{ inputs.task-definition-family }}:${{ steps.task-def-register.outputs.revision }})
        else
          task_arn=$(aws ecs run-task \
            --cluster ${{ inputs.cluster }} \
            --launch-type ${{ inputs.launch-type }} \
            --network-configuration 'awsvpcConfiguration=${{ env.vpc_configuration }}' \
            --output text \
            --query tasks[0].taskArn \
            --region ${{ inputs.region }} \
            --task-definition ${{ inputs.task-definition-family }}:${{ steps.task-def-register.outputs.revision }})
        fi
        echo "task_arn=$task_arn" >> $GITHUB_OUTPUT
        echo "task_id=${task_arn/*\//}" >> $GITHUB_OUTPUT

    - name: Wait until a task stopped
      shell: bash
      run: |
        aws ecs wait tasks-stopped \
          --cluster ${{ inputs.cluster }} \
          --tasks ${{ steps.run-task.outputs.task_arn }}

    - name: Install ecs-cli
      shell: bash
      env:
        ecs_cli_version: v1.21.0
      run: |
        sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-${{ env.ecs_cli_version }}
        sudo chmod +x /usr/local/bin/ecs-cli

    - name: Retrieve container logs from CloudWatch logs
      shell: bash
      id: logs
      run: |
        echo "::group::Retrieve container logs from CloudWatch logs"
        echo '::echo::on'
        out=$(ecs-cli logs --timestamps \
          --cluster ${{ inputs.cluster }} \
          --task-def ${{ inputs.task-definition-family }}:${{ steps.task-def-register.outputs.revision }} \
          --task-id ${{ steps.run-task.outputs.task_id }})
        out="${out//'%'/'%25'}"
        out="${out//$'\n'/'%0A'}"
        out="${out//$'\r'/'%0D'}"
        out="${out//$'^'/'d'}"
        echo "out=$out" >> $GITHUB_OUTPUT
        echo "::endgroup::"

    - name: Check exit code in tasks
      shell: bash
      id: task-exit-code
      run: |
        exitCode=$(aws ecs describe-tasks \
          --cluster ${{ inputs.cluster }} \
          --output text \
          --query tasks[0].containers[0].exitCode \
          --region ${{ inputs.region }} \
          --tasks ${{ steps.run-task.outputs.task_arn }})
        if [ "$exitCode" != "0" ]; then
          echo "detected run-task failure"
          exit $exitCode
        fi
